name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install dependencies
      run: apt install libwxgtk3.0-dev
    - name: Prepare CMake build
      working-directory: build
      run: cmake ..
    - name: Compile
      working-directory: build
      run: cmake --build . -j 4
